from numpy.core.fromnumeric import std


BREAK = 0
PITCHINDEX = 0
DURATIONINDEX = 1
INTERVALINDEX = 2
RESTINDEX = 3
# accumulative beat count
ACCUMULATIVEINDEX = 4
SEGMENTATIONINDEX = 5
ELEMENTINDEX = 6

BeatInMeasure = 16
AccumulativeWeight = 3

MINRPLENTH = 3


NUMBER_FEATURES = 22
NUMBER_SONGS = 97

INPUT_NAMES = []
INPUT_RATE = 0

FITNESS_WEIGHT = [ 1,1,1,100 ]