BREAK = 0
PITCHINDEX = 0
DURATIONINDEX = 1
INTERVALINDEX = 2
RESTINDEX = 3
# accumulative beat count
ACCUMULATIVEINDEX = 4
SEGMENTATIONINDEX = 5
BeatInMeasure = 16
AccumulativeWeight = 3

# RP
MINRPLENTH = 3
